# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the license found in the
# LICENSE file in the root directory of this source tree.


def logo():
    print("\n")
    print(r""" _____                 _ _____            _ 
|  _  |               (_)  ___|          | |
| | | |_ __ ___  _ __  _\ `--.  ___  __ _| |
| | | | '_ ` _ \| '_ \| |`--. \/ _ \/ _` | |
\ \_/ / | | | | | | | | /\__/ /  __/ (_| | |
 \___/|_| |_| |_|_| |_|_\____/ \___|\__,_|_|
""")

def help_eval():
    """Display help for the eval command."""
    print("\nUsage: omniseal eval [audio | image | video] [command] [options]\n")
    print("Available command:")
    print("  generate_watermark: Generate watermarks for the specified modality.")
    print("  detect_watermark: Detect watermarks in the specified modality.")
    print("Use 'omniseal eval <modality> --help' for more details on a specific command.\n")


def help_main():
    """Display help for the eval command."""
    print("\nUsage: omniseal [eval | leaderboard | info] [command] [options]\n")
    print("Available command:")
    print("  eval: Evaluate the model(s) for a specific dataset and modality.")
    print("  leaderboard: Commands related to Omniseal Bench leaderboard.")
    print("  info: Show information about the OmnisealBench models.")
    print("Use 'omniseal eval --help' or 'omniseal leaderboard --help' for more details on a specific command.\n")


def print_audio_help():
    """Display help for audio evaluation commands."""
    print("\nAudio Evaluation Commands:")
    print("  omniseal eval audio [generate_watermark | detect_watermark] [general options] [data options] [task-specific options] [model options] [slurm options]\n")
    print("Tasks:")
    print("  generate_watermark: Generate watermarks for audio dataset and compute quality metrics.")
    print("  detect_watermark: Detect watermarks in audio dataset.\n")
    print("Options:\n")
    print("\n----------------------------------------------------------")
    print("General options:\n")
    print("    --metrics                Metrics to compute (comma-separated).")
    print("    --result_dir             Directory to save results.")
    print("    --overwrite              Overwrite existing results.")
    print("    --seed                   Random seed for reproducibility.")
    print("    --num_workers            Number of workers for data loading.")
    print("    --num_samples            Number of samples to process.")
    print("    --show_progress          Show progress bars.")
    print("    --device                 Device to run the model on ('cpu' or 'cuda').")
    print("\n----------------------------------------------------------")
    print("Data options:\n")
    print("    --dataset_type          Type of dataset: 'hf' for HuggingFace, 'local' for local files.")
    print("    --padding                Padding strategy: 'longest', 'fixed', 'even', 'uneven'.")
    print("    --max_length             Maximum length of messages (if padding is 'fixed').")
    print("    --sample_rate            Sample rate for audio processing.")
    print("    --batch_size             Batch size for processing.")
    print("Task-specific options:\n")
    print("  (default):")
    print("    --config                 Path to the configuration file for the task.")
    print("    (all parameters in generate_watermark and detect_watermark)")
    print("\n")
    print("  generate_watermark:")
    print("    --dataset_name           Name of the dataset to evaluate (HuggingFace).")
    print("    --dataset_hf_subset      Category of the dataset (HuggingFace `name`).")
    print("    --dataset_split          Dataset split to use (e.g., 'test').")
    print("    --dataset_dir            Directory containing the dataset (local).")
    print("    --audio_pattern          Pattern to match audio files (local).")
    print("    --message_size           (Experimental) Sizes of messages to embed. To test the model that support multiple-sized message watermarking (comma-separated).")
    print("    --how_to_generate_message Method to generate messages: 'per_batch' or 'per_dataset'.")
    print("\n")
    print("  detect_watermark:\n")
    print("    --input_dir                  Directory containing the watermarked dataset.")
    print("    --audio_pattern              Pattern to match original audio files.")
    print("    --watermarked_audio_pattern  Pattern to match watermarked audio files (optional).")
    print("    --detection_threshold        Threshold for watermark detection.")
    print("    --message_threshold          Threshold for message detection.")
    print("    --detection_bits             Number of bits in the secret message.")
    print("    --attacks                    Attacks to apply to the audio files (optional).")
    print("  report:\n")
    print("    --input_dir                  Directory containing the results to report.")
    print("\n----------------------------------------------------------")
    print("Model options:\n")
    print("  --model                  Name of the model to use for watermarking.")
    print("  --model_kwargs           Additional keyword arguments for the model. Use\n")
    print("\n----------------------------------------------------------")
    print("SLURM options:\n")
    print("  --slurm                 Use SLURM for job scheduling.")
    print("  --launcher_args         Additional arguments for the SLURM launcher.")
    print("                          Permissible keys: partition, qos, account, log_dir, nodes, tasks_per_node,")
    print("                          gpus_per_node, cpus_per_task,")
    print("                          mem_gb, timeout_min, job_name, constraint.")    

def print_image_help():
    """Display help for image evaluation commands."""
    print("\nImage Evaluation Commands:")
    print("  omniseal eval image [generate_watermark | detect_watermark] [general options] [data options] [model options] [slurm options]\n")
    print("Tasks:")
    print("  generate_watermark: Generate watermarks for image dataset and compute quality metrics.")
    print("  detect_watermark: Detect watermarks in image dataset.\n")
    print("Options:\n")
    print("----------------------------------------------------------")
    print("General options:\n")
    print("    --metrics                Metrics to compute (comma-separated).")
    print("    --result_dir             Directory to save results.")
    print("    --overwrite              Overwrite existing results.")
    print("    --seed                   Random seed for reproducibility.")
    print("    --num_workers            Number of workers for data loading (0 means no parallel loading).")
    print("    --num_samples            Number of samples to process.")
    print("    --show_progress          Show progress bars.")
    print("    --device                 Device to run the model on ('cpu' or 'cuda').")
    print("\n----------------------------------------------------------")
    print("Data options:\n")
    print("  generate_watermark:")
    print("    --dataset_dir            Directory containing the dataset (local).")
    print("    --image_pattern          Pattern to match image files (local).")
    print("    --message_size           Sizes of messages to embed (comma-separated).")
    print("    --how_to_generate_message Method to generate messages: 'per_batch' or 'per_dataset'.")
    print("    --batch_size             Batch size for processing.")
    print("\n")
    print("  detect_watermark:\n")
    print("    --input_dir                  Directory containing the watermarked dataset.")
    print("    --image_pattern              Pattern to match original image files.")
    print("    --watermarked_image_pattern  Pattern to match watermarked image files (optional).")
    print("    --detection_threshold        Threshold for watermark detection.")
    print("    --message_threshold          Threshold for message detection.")
    print("    --detection_bits             Number of bits in the secret message.")
    print("    --attacks                    Attacks to apply to the image files (optional).")
    print("    --batch_size                 Batch size for processing.")
    print("  report:\n")
    print("    --input_dir                  Directory containing the results to report.")
    print("\n----------------------------------------------------------")
    print("Model options:\n")
    print("  --model                  Name of the model to use for watermarking (registered name or class).")
    print("  --model_kwargs           Additional keyword arguments for the model.\n")
    print("\n----------------------------------------------------------")
    print("SLURM options:\n")
    print("  --slurm                 Use SLURM for job scheduling.")
    print("  --slurm_config          SLURM config file.")
    print("  --launcher_args         Additional arguments for the SLURM launcher.")
    print("                          Permissible keys: partition, qos, account, log_dir, nodes, tasks_per_node,")
    print("                          gpus_per_node, cpus_per_task, mem_gb, timeout_min, job_name, constraint.")
    
def print_video_help():
    """Display help for video evaluation commands."""
    print("\nVideo Evaluation Commands:")
    print("  omniseal eval video [generate_watermark | detect_watermark] [general options] [data options] [model options] [slurm options]\n")
    print("Tasks:")
    print("  generate_watermark: Generate watermarks for video dataset and compute quality metrics.")
    print("  detect_watermark: Detect watermarks in video dataset.\n")
    print("Options:\n")
    print("----------------------------------------------------------")
    print("General options:\n")
    print("    --metrics                Metrics to compute (comma-separated).")
    print("    --result_dir             Directory to save results.")
    print("    --overwrite              Overwrite existing results.")
    print("    --seed                   Random seed for reproducibility.")
    print("    --num_workers            Number of workers for data loading (0 means no parallel loading).")
    print("    --num_samples            Number of samples to process.")
    print("    --show_progress          Show progress bars.")
    print("    --device                 Device to run the model on ('cpu' or 'cuda').")
    print("\n----------------------------------------------------------")
    print("Data options:\n")
    print("  generate_watermark:")
    print("    --dataset_dir            Directory containing the dataset (local).")
    print("    --video_pattern          Pattern to match video files (local).")
    print("    --output_resolution      Output resolution for generated videos.")
    print("    --max_frames             Maximum number of frames per video.")
    print("    --fps                    Frames per second for output videos.")
    print("    --crf                    Constant Rate Factor for video encoding.")
    print("    --video_codec            Video codec to use for encoding (default: libx264).")
    print("  detect_watermark:")
    print("    --input_dir                  Directory containing the watermarked dataset.")
    print("    --original_video_pattern     Pattern to match original video files.")
    print("    --watermarked_video_pattern  Pattern to match watermarked video files (optional).")
    print("    --detection_threshold        Threshold for watermark detection.")
    print("    --message_threshold          Threshold for message detection.")
    print("    --detection_bits             Number of bits in the secret message.")
    print("    --attacks                    Attacks to apply to the video files (optional).")
    print("    --batch_size                 Batch size for processing.")
    print("  report:\n")
    print("    --input_dir                  Directory containing the results to report.")
    print("\n----------------------------------------------------------")
    print("Model options:\n")
    print("  --model                  Name of the model to use for watermarking (registered name or class).")
    print("  --model_kwargs           Additional keyword arguments for the model.\n")
    print("\n----------------------------------------------------------")
    print("SLURM options:\n")
    print("  --slurm                 Use SLURM for job scheduling.")
    print("  --slurm_config          SLURM config file.")
    print("  --launcher_args         Additional arguments for the SLURM launcher.")
    print("                          Permissible keys: partition, qos, account, log_dir, nodes, tasks_per_node,")
    print("                          gpus_per_node, cpus_per_task, mem_gb, timeout_min, job_name, constraint.")


def print_leaderboard_help():
    """Display help for leaderboard command."""
    print("\nLeaderboard Command:")
    print("  omniseal leaderboard export [options]]\n")
    print("Options:")
    print("  source: Source containing the results to export to the leaderboard format.")
    print("  modality: Modality to add to the exported filenames.")
    print("  dataset_label: Label of the dataset to be used in the leaderboard.")
    print("  target: Target directory to save the formatted leaderboard results (JSON & CSV).")
    print("  samples: Comma-separated list of sample IDs to include in the export (optional).")
    print("\nThis command will read the results from the specified input directory and export them to a JSON file in a structured format suitable for leaderboard display.")


def print_info_help():
    """Display help for info command."""
    print("\nInfo Command:")
    print("  omniseal info [model | models | attacks] [options]]\n")
    print("Options for models | attacks:")
    print("  audio                  Show default audio models.")
    print("  image                  Show default image models.")
    print("  video                  Show default video models.")
    print("Options for specific model:")
    print("  --model_name           Name of the model to show information about.")
    print("\nThis command will display information about the specified model or list of default models for a specific modality.")
