model: vae_small

unet_plus_small:
  msg_processor:
    nbits: 16
    hidden_size: 32     # nbits * 2
    msg_processor_type: 'binary+concat'
  unet:
    in_channels: 3
    out_channels: 3
    z_channels: 16
    num_blocks: 3
    activation: 'silu'
    normalization: 'rms'
    z_channels_mults: [1, 2, 4]
    last_tanh: True

unet_plus_small_bw:
  msg_processor:
    nbits: 16
    hidden_size: 32     # nbits * 2
    msg_processor_type: 'binary+concat'
  unet:
    in_channels: 3
    out_channels: 3
    z_channels: 16
    num_blocks: 3
    activation: 'silu'
    normalization: 'rms'
    z_channels_mults: [1, 2, 4]
    last_tanh: True
    bw: True

unet_plus_small_bw_zero_init:
  msg_processor:
    nbits: 16
    hidden_size: 32     # nbits * 2
    msg_processor_type: 'binary+concat'
  unet:
    in_channels: 3
    out_channels: 3
    z_channels: 16
    num_blocks: 3
    activation: 'silu'
    normalization: 'rms'
    z_channels_mults: [1, 2, 4]
    last_tanh: True
    bw: True
    zero_init: True

unet_plus:
  msg_processor:
    nbits: 16
    hidden_size: 32     # nbits * 2
    msg_processor_type: 'binary+concat'
  unet:
    in_channels: 3
    out_channels: 3
    z_channels: 32
    num_blocks: 3
    activation: 'silu'
    normalization: 'rms'
    z_channels_mults: [1, 2, 4]
    last_tanh: True

unet_plus_big:
  msg_processor:
    nbits: 16
    hidden_size: 32     # nbits * 2
    msg_processor_type: 'binary+concat'
  unet:
    in_channels: 3
    out_channels: 3
    z_channels: 32
    num_blocks: 4
    activation: 'silu'
    normalization: 'rms'
    z_channels_mults: [1, 2, 4, 8]
    last_tanh: True

unet_plus_big_bw:
  msg_processor:
    nbits: 16
    hidden_size: 32     # nbits * 2
    msg_processor_type: 'binary+concat'
  unet:
    in_channels: 3
    out_channels: 3
    z_channels: 32
    num_blocks: 4
    activation: 'silu'
    normalization: 'rms'
    z_channels_mults: [1, 2, 4, 8]
    last_tanh: True
    bw: True
  
unet_plus_bigger:
  msg_processor:
    nbits: 16
    hidden_size: 32     # nbits * 2
    msg_processor_type: 'binary+concat'
  unet:
    in_channels: 3
    out_channels: 3
    z_channels: 64
    num_blocks: 4
    activation: 'silu'
    normalization: 'rms'
    z_channels_mults: [1, 2, 4, 8]


unet_plus_small_notanh:
  msg_processor:
    nbits: 16
    hidden_size: 32     # nbits * 2
    msg_processor_type: 'binary+concat'
  unet:
    in_channels: 3
    out_channels: 3
    z_channels: 16
    num_blocks: 3
    activation: 'silu'
    normalization: 'rms'
    z_channels_mults: [1, 2, 4]
    last_tanh: False

unet_plus_notanh:
  msg_processor:
    nbits: 16
    hidden_size: 32     # nbits * 2
    msg_processor_type: 'binary+concat'
  unet:
    in_channels: 3
    out_channels: 3
    z_channels: 32
    num_blocks: 3
    activation: 'silu'
    normalization: 'rms'
    z_channels_mults: [1, 2, 4]
    last_tanh: False

unet_plus_big_notanh:
  msg_processor:
    nbits: 16
    hidden_size: 32     # nbits * 2
    msg_processor_type: 'binary+concat'
  unet:
    in_channels: 3
    out_channels: 3
    z_channels: 32
    num_blocks: 4
    activation: 'silu'
    normalization: 'rms'
    z_channels_mults: [1, 2, 4, 8]
    last_tanh: False
  
unet:
  msg_processor:
    nbits: 16
    hidden_size: 32     # nbits * 2
    msg_processor_type: 'binary+concat'
  unet:
    in_channels: 3
    out_channels: 3
    num_blocks: 3  # in the bottleneck
    z_channels: 32
    last_tanh: True

unet_notanh:
  msg_processor:
    nbits: 16
    hidden_size: 32     # nbits * 2
    msg_processor_type: 'binary+concat'
  unet:
    in_channels: 3
    out_channels: 3
    num_blocks: 3  # in the bottleneck
    z_channels: 32
    last_tanh: False
  
unet_big:
  msg_processor:
    nbits: 16
    hidden_size: 64     # nbits * 2
    msg_processor_type: 'binary+concat'
  unet:
    in_channels: 3
    out_channels: 3
    num_blocks: 4  # in the bottleneck
    z_channels: 128
    last_tanh: True
  
unet_bigger:
  msg_processor:
    nbits: 16
    hidden_size: 64     # nbits * 2
    msg_processor_type: 'binary+concat'
  unet:
    in_channels: 3
    out_channels: 3
    num_blocks: 6  # in the bottleneck
    z_channels: 196
    last_tanh: True

hidden:
  num_blocks: 4  # in the bottleneck
  num_bits: 16
  z_channels: 64
  normalization: 'group'
  last_tanh: True

vae_small:
  msg_processor:
    nbits: 16
    hidden_size: 32     # nbits * 2
    msg_processor_type: 'binary+concat'
  encoder:
    in_channels: 3
    z_channels: 4
    resolution: 256  # only used for attn_resolutions
    out_ch: 3
    ch: 32
    ch_mult: [1, 1, 1, 2]
    num_res_blocks: 2
    attn_resolutions: []
    dropout: 0.0
    double_z: False
  decoder:
    in_channels: 3
    z_channels: 36      # hidden_size + z_channels
    resolution: 256
    out_ch: 3
    ch: 32
    ch_mult: [1, 1, 1, 2]
    num_res_blocks: 2
    attn_resolutions: []
    dropout: 0.0
    tanh_out: True


vae_small_yuv:
  yuv: True
  msg_processor:
    nbits: 16
    hidden_size: 32     # nbits * 2
    msg_processor_type: 'binary+concat'
  encoder:
    in_channels: 3
    z_channels: 4
    resolution: 256  # only used for attn_resolutions
    out_ch: 3
    ch: 32
    ch_mult: [1, 1, 1, 2]
    num_res_blocks: 2
    attn_resolutions: []
    dropout: 0.0
    double_z: False
  decoder:
    in_channels: 3
    z_channels: 36      # hidden_size + z_channels
    resolution: 256
    out_ch: 3
    ch: 32
    ch_mult: [1, 1, 1, 2]
    num_res_blocks: 2
    attn_resolutions: []
    dropout: 0.0
    tanh_out: True

vae_small_bw:
  msg_processor:
    nbits: 16
    hidden_size: 32     # nbits * 2
    msg_processor_type: 'binary+concat'
  encoder:
    in_channels: 3
    z_channels: 4
    resolution: 256  # only used for attn_resolutions
    out_ch: 3
    ch: 32
    ch_mult: [1, 1, 1, 2]
    num_res_blocks: 2
    attn_resolutions: []
    dropout: 0.0
    double_z: False
  decoder:
    in_channels: 3
    z_channels: 36      # hidden_size + z_channels
    resolution: 256
    out_ch: 3
    ch: 32
    ch_mult: [1, 1, 1, 2]
    num_res_blocks: 2
    attn_resolutions: []
    dropout: 0.0
    tanh_out: True
    bw: True
  
vae_big:
  msg_processor:
    nbits: 16
    hidden_size: 32     # nbits * 2
    msg_processor_type: 'binary+concat'
  encoder:
    in_channels: 3
    z_channels: 4
    resolution: 256  # only used for attn_resolutions
    out_ch: 3
    ch: 64
    ch_mult: [1, 1, 2, 2]
    num_res_blocks: 2
    attn_resolutions: []
    dropout: 0.0
    double_z: False
  decoder:
    in_channels: 3
    z_channels: 36      # hidden_size + z_channels
    resolution: 256
    out_ch: 3
    ch: 64
    ch_mult: [1, 1, 2, 2]
    num_res_blocks: 2
    attn_resolutions: []
    dropout: 0.0
    tanh_out: True

  #### Large ####
  # msg_processor:
  #   nbits: 16
  #   hidden_size: 32     # nbits * 2
  #   msg_processor_type: 'binary+concat'

  # encoder:
  #   in_channels: 3
  #   z_channels: 4
  #   resolution: 256  # only used for attn_resolutions
  #   out_ch: 3
  #   ch: 32
  #   ch_mult: [1, 1, 1, 2]
  #   num_res_blocks: 4
  #   attn_resolutions: []
  #   dropout: 0.0
  #   double_z: False

  # decoder:
  #   in_channels: 3
  #   z_channels: 36      # hidden_size + z_channels
  #   resolution: 256
  #   out_ch: 3
  #   ch: 64
  #   ch_mult: [1, 1, 1, 2]
  #   num_res_blocks: 4
  #   attn_resolutions: []
  #   dropout: 0.0
  #   tanh_out: True
    
# Config from the VAE of SD is:
#   double_z: true
#   z_channels: 4
#   resolution: 256
#   in_channels: 3
#   out_ch: 3
#   ch: 128
#   ch_mult:
#   - 1
#   - 2
#   - 4
#   - 4
#   num_res_blocks: 2
#   attn_resolutions: []
#   dropout: 0.0